HgabkaNodeBundle_widgets:
    resource: '@HgabkaNodeBundle/Controller/WidgetsController.php'
    type:     annotation
    prefix:   /nodewidgets

HgabkaNodeBundle_nodes:
    resource: '@HgabkaNodeBundle/Controller/NodeAdminController.php'
    type:     annotation
    prefix:   /nodes

hgabka_node.url_replace.controller:
    resource: '@HgabkaNodeBundle/Controller/UrlReplaceController.php'
    type:     annotation
    prefix:   /url-replace
