HgabkaNodeBundle_widgets:
    resource: '@HgabkaNodeBundle/Controller/WidgetsController.php'
    type:     attribute
    prefix:   /cms/nodewidgets

HgabkaNodeBundle_nodes:
    resource: '@HgabkaNodeBundle/Controller/NodeAdminController.php'
    type:     attribute
    prefix:   /cms/nodes

hgabka_node.url_replace.controller:
    resource: '@HgabkaNodeBundle/Controller/UrlReplaceController.php'
    type:     attribute
    prefix:   /cms/url-replace
