parameters:
    hgabka_node.version_timeout: 3600
    hgabka_node.slugrouter.class: 'Hgabka\NodeBundle\Router\SlugRouter'
    hgabka_node.sluglistener.class: 'Hgabka\NodeBundle\EventListener\SlugListener'
    hgabka_node.helper.url.class: Hgabka\NodeBundle\Helper\URLHelper
    hgabka_node.url_replace.twig.class: Hgabka\NodeBundle\Twig\UrlReplaceTwigExtension
    hgabka_node.url_chooser.lazy_increment: 2
    hgabka_multi_domain.url_replace.controller.class: Hgabka\NodeBundle\Controller\UrlReplaceController

services:
    hgabka_node.admin.node:
        class: Hgabka\NodeBundle\Admin\NodeAdmin
        tags:
        - { name: sonata.admin, manager_type: orm, group: hg_node.group, icon: '<i class="fa fa-sticky-note"></i>', label: hg_node.group, label_catalogue: 'HgabkaNodeBundle', label_translator_strategy: 'sonata.admin.label.strategy.underscore' }
        arguments: [null, Hgabka\NodeBundle\Entity\Node, HgabkaNodeBundle:NodeAdmin]

    hgabka_node.nodetranslation.listener:
        class: Hgabka\NodeBundle\EventListener\NodeTranslationListener
        arguments: ['@session', '@hgabka_utils.logger' , '@hgabka_utils.slugifier', '@hgabka_utils.hgabka_utils', '@hgabka_node.pages_configuration']
        calls:
            - [ 'setRequestStack', ['@request_stack'] ]
        tags:
            - { name: 'doctrine.event_listener', event: 'onFlush', method: 'onFlush' }
            - { name: 'doctrine.event_listener', event: 'postFlush', method: 'postFlush' }
            - { name: 'doctrine.event_listener', event: 'prePersist', method: 'prePersist' }
            - { name: 'doctrine.event_listener', event: 'preUpdate', method: 'preUpdate' }

    hgabka_node.form.type.urlchooser:
        class: Hgabka\NodeBundle\Form\Type\URLChooserType
        tags:
            - { name: 'form.type' }

    hgabka_node.form.type.slug:
        class: Hgabka\NodeBundle\Form\Type\SlugType
        arguments: ['@hgabka_utils.slugifier']
        tags:
            - { name: 'form.type' }

    hgabka_node.form.type.nodechoice:
        class: Hgabka\NodeBundle\Form\NodeChoiceType
        arguments:
            - "@request_stack"
        tags:
            - { name: form.type }

    hgabka_node.admin_node.publisher:
        class: Hgabka\NodeBundle\Helper\NodeAdmin\NodeAdminPublisher
        arguments: ['@doctrine.orm.entity_manager', '@security.token_storage', '@security.authorization_checker', '@event_dispatcher', '@hgabka_utils.clone.helper']

    hgabka_node.admin_node.node_version_lock_helper:
        class: Hgabka\NodeBundle\Helper\NodeAdmin\NodeVersionLockHelper
        arguments: ['@service_container', '@doctrine.orm.entity_manager']

    hgabka_node.actions_menu_builder:
        class: Hgabka\NodeBundle\Helper\Menu\ActionsMenuBuilder
        arguments: ['@knp_menu.factory', '@doctrine.orm.entity_manager', '@router', '@event_dispatcher', '@security.authorization_checker', '@hgabka_node.pages_configuration' ]

    hgabka_node.menu.sub_actions:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory: ['@hgabka_node.actions_menu_builder', createSubActionsMenu]
        tags:
            - { name: 'knp_menu.menu', alias: 'sub_actions' } # The alias is what is used to retrieve the menu

    hgabka_node.menu.actions:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory: ['@hgabka_node.actions_menu_builder', createActionsMenu]
        tags:
            - { name: 'knp_menu.menu', alias: 'actions' } # The alias is what is used to retrieve the menu

    hgabka_node.menu.top_actions:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory: ['@hgabka_node.actions_menu_builder', createTopActionsMenu]
        tags:
            - { name: 'knp_menu.menu', alias: 'top_actions' } # The alias is what is used to retrieve the menu

    hgabka_node.fix_date.listener:
        class: Hgabka\NodeBundle\EventListener\FixDateListener
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse, priority: -100 }

    hgabka_node.edit_node.listener:
        class: Hgabka\NodeBundle\EventListener\NodeListener
        arguments: ['@security.authorization_checker', '@hgabka_utils.permissionadmin', '@hgabka_utils.security.acl.permission.map']
        tags:
            - { name: kernel.event_listener, event: hgabka_node.adaptForm, method: adaptForm }

    hgabka_node.log_page_events.subscriber:
        class: Hgabka\NodeBundle\EventListener\LogPageEventsSubscriber
        arguments: ['@hgabka_utils.logger', '@security.token_storage']
        tags:
            - { name: kernel.event_subscriber }

    hgabka_node.slugrouter:
        class: '%hgabka_node.slugrouter.class%'
        arguments: ['@service_container']
        tags:
            - { name: router, priority: 0 }

    hgabka_node.pages_configuration.twig_extension:
        class: Hgabka\NodeBundle\Twig\PagesConfigurationTwigExtension
        public: false
        arguments: [ '@hgabka_node.pages_configuration' ]
        tags:
            - { name: twig.extension }

    hgabka_node.url_replace.twig.extension:
        class: "%hgabka_node.url_replace.twig.class%"
        arguments:
            - "@hgabka_node.helper.url"
        tags:
            - { name: twig.extension }

    hgabka_node.page_creator_service:
        class: Hgabka\NodeBundle\Helper\Services\PageCreatorService
        calls:
            - [ setEntityManager, [ '@doctrine.orm.entity_manager' ] ]
            - [ setACLPermissionCreatorService, [ '@hgabka_node.acl_permission_creator_service' ] ]
            - [ setUserEntityClass, [ '%fos_user.model.user.class%' ] ]

    hgabka_node.acl_permission_creator_service:
        class: Hgabka\NodeBundle\Helper\Services\ACLPermissionCreatorService
        calls:
            - [ setAclProvider, [ '@security.acl.provider' ] ]
            - [ setObjectIdentityRetrievalStrategy, [ '@security.acl.object_identity_retrieval_strategy' ] ]

    hgabka_node.doctrine_mapping.listener:
        class: Hgabka\NodeBundle\EventListener\MappingListener
        arguments: ['%fos_user.model.user.class%']
        tags:
            - { name: doctrine.event_listener, event: loadClassMetadata }

    hgabka_node.slug.listener:
        class: '%hgabka_node.sluglistener.class%'
        arguments: ['@doctrine.orm.entity_manager','@controller_resolver', '@event_dispatcher']
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

    hgabka_node.slug.security.listener:
        class: Hgabka\NodeBundle\EventListener\SlugSecurityListener
        arguments: ['@doctrine.orm.entity_manager', '@security.authorization_checker', '@hgabka_node.node_menu']
        tags:
            - { name: kernel.event_listener, event: hgabka_node.slug.security, method: onSlugSecurityEvent }

    hgabka_node.render.context.listener:
        class: Hgabka\NodeBundle\EventListener\RenderContextListener
        arguments: ['@templating', '@doctrine.orm.entity_manager']
        tags:
            - { name: kernel.event_listener, event: kernel.view, method: onKernelView }

    hgabka_node.node_menu:
        class: Hgabka\NodeBundle\Helper\NodeMenu
        arguments: ['@doctrine.orm.entity_manager', '@security.token_storage', '@hgabka_utils.acl.helper', '@hgabka_utils.hgabka_utils']

    hgabka_node.node.twig.extension:
        class: Hgabka\NodeBundle\Twig\NodeTwigExtension
        arguments: ['@doctrine.orm.entity_manager', '@router', '@hgabka_node.node_menu', '@request_stack']
        tags:
            - { name: twig.extension }

    hgabka_node.helper.url:
        class: "%hgabka_node.helper.url.class%"
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@router"
            - "@logger"
            - "@request_stack"
            - "@hgabka_utils.hgabka_utils"

    hgabka_node.url_replace.controller:
        class: "%hgabka_multi_domain.url_replace.controller.class%"
        arguments:
            - "@hgabka_node.helper.url"

    hgabka_node.command.acl:
        class: Hgabka\NodeBundle\Command\InitAclCommand
        calls:
            - [ setOidStrategy, [ '@security.acl.object_identity_retrieval_strategy' ] ]
        tags:
            - { name: console.command }

    hgabka_node.command.convert_sequence:
        class: Hgabka\NodeBundle\Command\ConvertSequenceNumberToWeightCommand
        tags:
        - { name: console.command }

    hgabka_node.command.cron_update_node:
        class: Hgabka\NodeBundle\Command\CronUpdateNodeCommand
        tags:
        - { name: console.command }

    hgabka_node.command.fix_timestamp:
        class: Hgabka\NodeBundle\Command\FixTimestampsCommand
        tags:
        - { name: console.command }

    hgabka_node.command.update_urls:
        class: Hgabka\NodeBundle\Command\UpdateUrlsCommand
        tags:
        - { name: console.command }

    Hgabka\NodeBundle\Controller\UrlReplaceController: "@hgabka_node.url_replace.controller"
