parameters:
    hgabka_node.version_timeout: 3600
    hgabka_node.slugrouter.class: 'Hgabka\NodeBundle\Router\SlugRouter'
    hgabka_node.sluglistener.class: 'Hgabka\NodeBundle\EventListener\SlugListener'
    hgabka_node.helper.url.class: Hgabka\NodeBundle\Helper\URLHelper
    hgabka_node.url_replace.twig.class: Hgabka\NodeBundle\Twig\UrlReplaceTwigExtension
    hgabka_node.url_chooser.lazy_increment: 2
    hgabka_multi_domain.url_replace.controller.class: Hgabka\NodeBundle\Controller\UrlReplaceController

services:
    hgabka_node.admin.node:
        class: Hgabka\NodeBundle\Admin\NodeAdmin
        tags:
        - { name: sonata.admin, manager_type: orm, group: hg_node.group, icon: '<i class="fa fa-sticky-note"></i>', label: hg_node.admin.node.label, label_catalogue: 'HgabkaNodeBundle', label_translator_strategy: 'sonata.admin.label.strategy.underscore' }
        arguments: [null, Hgabka\NodeBundle\Entity\Node, Hgabka\NodeBundle\Controller\NodeAdminController]

    hgabka_node.nodetranslation.listener:
        class: Hgabka\NodeBundle\EventListener\NodeTranslationListener
        arguments: ['@session', '@hgabka_utils.logger' , '@hgabka_utils.slugifier', '@hgabka_utils.hgabka_utils', '@hgabka_node.pages_configuration']
        calls:
            - [ 'setRequestStack', ['@request_stack'] ]
        tags:
            - { name: 'doctrine.event_listener', event: 'onFlush', method: 'onFlush' }
            - { name: 'doctrine.event_listener', event: 'postFlush', method: 'postFlush' }
            - { name: 'doctrine.event_listener', event: 'prePersist', method: 'prePersist' }
            - { name: 'doctrine.event_listener', event: 'preUpdate', method: 'preUpdate' }

    hgabka_node.menu.adaptor.pages:
        class: Hgabka\NodeBundle\Helper\Menu\PageMenuAdaptor
        arguments: ['@doctrine.orm.entity_manager', '@hgabka_utils.acl.native.helper', '@hgabka_node.pages_configuration']
        tags:
        -  { name: 'hgabka_utils.menu.adaptor' }


    hgabka_node.form.type.urlchooser:
        class: Hgabka\NodeBundle\Form\Type\URLChooserType
        tags:
            - { name: 'form.type' }

    hgabka_node.form.type.slug:
        class: Hgabka\NodeBundle\Form\Type\SlugType
        arguments: ['@hgabka_utils.slugifier']
        tags:
            - { name: 'form.type' }

    hgabka_node.form.type.nodechoice:
        class: Hgabka\NodeBundle\Form\NodeChoiceType
        arguments:
            - '@request_stack'
            - '@hgabka_node.node_manager'
        tags:
            - { name: form.type }

    Hgabka\NodeBundle\Helper\NodeAdmin\NodeAdminPublisher:
        public: true
        autowire: true
        arguments: ['@doctrine.orm.entity_manager', '@security.token_storage', '@security.authorization_checker', '@event_dispatcher', '@hgabka_utils.clone.helper']

    hgabka_node.admin_node.node_version_lock_helper:
        class: Hgabka\NodeBundle\Helper\NodeAdmin\NodeVersionLockHelper
        arguments: ['@service_container', '@doctrine.orm.entity_manager']

    Hgabka\NodeBundle\Search\NodeSearcher:
        autowire: true
        arguments: ['@doctrine.orm.entity_manager', '@hgabka_utils.hgabka_utils']

    Hgabka\NodeBundle\Helper\Menu\ActionsMenuBuilder:
        public: true
        arguments: ['@knp_menu.factory', '@doctrine.orm.entity_manager', '@router', '@event_dispatcher', '@security.authorization_checker', '@hgabka_node.pages_configuration', '@sonata.admin.pool', '@hgabka_utils.hgabka_utils', '@request_stack' ]

    hgabka_node.menu.sub_actions:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory: ['@hgabka_node.actions_menu_builder', createSubActionsMenu]
        tags:
            - { name: 'knp_menu.menu', alias: 'sub_actions' } # The alias is what is used to retrieve the menu

    hgabka_node.menu.actions:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory: ['@hgabka_node.actions_menu_builder', createActionsMenu]
        tags:
            - { name: 'knp_menu.menu', alias: 'actions' } # The alias is what is used to retrieve the menu

    hgabka_node.menu.top_actions:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory: ['@hgabka_node.actions_menu_builder', createTopActionsMenu]
        tags:
            - { name: 'knp_menu.menu', alias: 'top_actions' } # The alias is what is used to retrieve the menu

    hgabka_node.fix_date.listener:
        class: Hgabka\NodeBundle\EventListener\FixDateListener
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse, priority: -100 }

    hgabka_node.edit_node.listener:
        class: Hgabka\NodeBundle\EventListener\NodeListener
        arguments: ['@security.authorization_checker', '@hgabka_utils.permissionadmin', '@hgabka_utils.security.acl.permission.map']
        tags:
            - { name: kernel.event_listener, event: hgabka_node.adaptForm, method: adaptForm }

    hgabka_node.log_page_events.subscriber:
        class: Hgabka\NodeBundle\EventListener\LogPageEventsSubscriber
        arguments: ['@hgabka_utils.logger', '@security.token_storage']
        tags:
            - { name: kernel.event_subscriber }

    hgabka_node.node_locale.subscriber:
        class: Hgabka\NodeBundle\EventListener\NodeLocaleListener
        arguments: ['@session', '@hgabka_utils.hgabka_utils']
        tags:
            - { name: kernel.event_subscriber }

    hgabka_node.slugrouter:
        class: '%hgabka_node.slugrouter.class%'
        arguments: ['@service_container', '@hgabka_utils.hgabka_utils']
        tags:
            - { name: router, priority: 100 }

    hgabka_node.pages_configuration.twig_extension:
        class: Hgabka\NodeBundle\Twig\PagesConfigurationTwigExtension
        public: false
        arguments: [ '@hgabka_node.pages_configuration' ]
        tags:
            - { name: twig.extension }

    hgabka_node.url_replace.twig.extension:
        class: '%hgabka_node.url_replace.twig.class%'
        arguments:
            - '@hgabka_node.helper.url'
        tags:
            - { name: twig.extension }

    Hgabka\NodeBundle\Helper\Services\PageCreatorService:
        autowire: true
        calls:
            - [ setEntityManager, [ '@doctrine.orm.entity_manager' ] ]
            - [ setACLPermissionCreatorService, [ '@hgabka_node.acl_permission_creator_service' ] ]
            - [ setUserEntityClass, [ '%fos_user.model.user.class%' ] ]

    hgabka_node.page_creator_service:
        alias: Hgabka\NodeBundle\Helper\Services\PageCreatorService
  
    Hgabka\NodeBundle\Helper\Services\ACLPermissionCreatorService:
        public: true
        calls:
            - [ setAclProvider, [ '@security.acl.provider' ] ]
            - [ setObjectIdentityRetrievalStrategy, [ '@security.acl.object_identity_retrieval_strategy' ] ]

    hgabka_node.acl_permission_creator_service:
        alias: Hgabka\NodeBundle\Helper\Services\ACLPermissionCreatorService

    hgabka_node.doctrine_mapping.listener:
        class: Hgabka\NodeBundle\EventListener\MappingListener
        arguments: ['%hgabka_utils.backend_user_class%']
        tags:
            - { name: doctrine.event_listener, event: loadClassMetadata }

    hgabka_node.slug.listener:
        class: '%hgabka_node.sluglistener.class%'
        arguments: ['@doctrine.orm.entity_manager','@controller_resolver', '@event_dispatcher']
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

    hgabka_node.slug.security.listener:
        class: Hgabka\NodeBundle\EventListener\SlugSecurityListener
        arguments: ['@doctrine.orm.entity_manager', '@security.authorization_checker', '@hgabka_node.node_menu']
        tags:
            - { name: kernel.event_listener, event: hgabka_node.slug.security, method: onSlugSecurityEvent }

    hgabka_node.render.context.listener:
        class: Hgabka\NodeBundle\EventListener\RenderContextListener
        arguments: ['@twig', '@doctrine.orm.entity_manager']
        tags:
            - { name: kernel.event_listener, event: kernel.view, method: onKernelView }

    Hgabka\NodeBundle\Helper\NodeMenu:
        public: true
        arguments: ['@doctrine.orm.entity_manager', '@security.token_storage', '@hgabka_utils.acl.helper', '@hgabka_utils.hgabka_utils']

    hgabka_node.node_menu:
        alias: Hgabka\NodeBundle\Helper\NodeMenu

    hgabka_node.node.twig.extension:
        class: Hgabka\NodeBundle\Twig\NodeTwigExtension
        arguments: ['@hgabka_node.node_menu', '@request_stack', '@hgabka_utils.hgabka_utils', '@hgabka_node.node_manager']
        tags:
            - { name: twig.extension }

    Hgabka\NodeBundle\Helper\URLHelper:
        class: '%hgabka_node.helper.url.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@router'
            - '@logger'
            - '@request_stack'
            - '@hgabka_utils.hgabka_utils'

    Hgabka\NodeBundle\Controller\UrlReplaceController:
        public: true
        arguments:
            - '@hgabka_node.helper.url'
        tags: ['controller.service_arguments']

    Hgabka\NodeBundle\Controller\LinkPageController:
        public: true
        arguments:
            - '@hgabka_node.helper.url'
        tags: ['controller.service_arguments']

    hgabka_node.url_replace.controller:
        alias: Hgabka\NodeBundle\Controller\UrlReplaceController

    hgabka_node.actions_menu_builder:
        alias: Hgabka\NodeBundle\Helper\Menu\ActionsMenuBuilder

    Hgabka\NodeBundle\Command\InitAclCommand:
        autowire: true
        autoconfigure: true
        calls:
            - [ setAclProvider, [ '@security.acl.provider' ] ]
            - [ setOiaStrategy, [ '@security.acl.object_identity_retrieval_strategy' ] ]
        
    Hgabka\NodeBundle\Command\ConvertSequenceNumberToWeightCommand:
        autowire: true
        autoconfigure: true

    Hgabka\NodeBundle\Command\CronUpdateNodeCommand:
        autowire: true
        autoconfigure: true

    Hgabka\NodeBundle\Command\FixTimestampsCommand:
        autowire: true
        autoconfigure: true

    Hgabka\NodeBundle\Command\UpdateUrlsCommand:
        autowire: true
        autoconfigure: true

    hgabka_node.admin_node.publisher:
        alias: Hgabka\NodeBundle\Helper\NodeAdmin\NodeAdminPublisher

    Hgabka\NodeBundle\Form\NodeMenuTabAdminType:
        autowire: true
        autoconfigure: true

    Hgabka\NodeBundle\Controller\SlugController:
        autoconfigure: true
        autowire: true
        tags: ['controller.service_arguments']

    Hgabka\NodeBundle\Controller\WidgetsController:
        autoconfigure: true
        autowire: true
        tags: ['controller.service_arguments']

    hgabka_node.node_manager:
        alias: Hgabka\NodeBundle\Helper\NodeManager

    hgabka_node.helper.url:
        alias: Hgabka\NodeBundle\Helper\URLHelper

    Hgabka\NodeBundle\Helper\NodeManager:
        autoconfigure: true
        autowire: true
        
    Hgabka\NodeBundle\NodeAdminController:
        autoconfigure: true
        autowire: true

  
